apiVersion: intent.automation.dcn.ssu.ac.kr/v1
kind: Profile
metadata:
  name: clusterapi-resource-template-default
  kind: Infrastructure
  type: ClusterAPITemplate
  namespace: default
  revision: 1.0.0
spec:
  values:
    filename: cluster-template.yaml
    url: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/release
    version: v0.7.0