apiVersion: intent.automation.dcn.ssu.ac.kr/v1
kind: Profile
metadata:
  name: flannel-default
  namespace: default
  labels:
      kind: Infrastructure
      type: CNITemplate
      revision: 1.0.0
spec:
  values:
    cni: flannel
    version: "0.20.0"
    podCIDR: "[10.244.0.0/16]"
    serviceCIDR: "[10.243.0.0/16]"