OPENSTACK_IMAGE_NAME:                   "OPENSTACK_IMAGE_NAME"
OPENSTACK_EXTERNAL_NETWORK_ID:          "OPENSTACK_EXTERNAL_NETWORK_ID"
OPENSTACK_DNS_NAMESERVERS:              "OPENSTACK_DNS_NAMESERVERS"
OPENSTACK_SSH_KEY_NAME:                 "OPENSTACK_SSH_KEY_NAME"
OPENSTACK_CLOUD_CACERT_B64:             "OPENSTACK_CLOUD_CACERT_B64"
OPENSTACK_CLOUD_PROVIDER_CONF_B64:      "OPENSTACK_CLOUD_PROVIDER_CONF_B64"
OPENSTACK_CLOUD_YAML_B64:               "OPENSTACK_CLOUD_YAML_B64"
OPENSTACK_FAILURE_DOMAIN:               "OPENSTACK_FAILURE_DOMAIN"
OPENSTACK_CLOUD:                        "OPENSTACK_CLOUD"
OPENSTACK_CONTROL_PLANE_MACHINE_FLAVOR: "OPENSTACK_CONTROL_PLANE_MACHINE_FLAVOR"
OPENSTACK_NODE_MACHINE_FLAVOR:          "OPENSTACK_NODE_MACHINE_FLAVOR"