apiVersion: intent.automation.dcn.ssu.ac.kr/v1
kind: LogicalCluster
metadata:
  name: intra-edges
  labels:
    automation.dcn.ssu.ac.kr/project: intra-edges
    tenant: intra-edges
spec:
  clusters:
    - cluster:
      name: edge-1
      metadata:
        labels:
          automation.dcn.ssu.ac.kr/location: site-1
          automation.dcn.ssu.ac.kr/managed-by: emco-mec-central-mgmt
      spec:
        clustercatalog: openstack-medium-catalog
    - cluster:
      name: edge-2
      metadata:
        labels:
          automation.dcn.ssu.ac.kr/location: site-1
          automation.dcn.ssu.ac.kr/managed-by: emco-mec-central-mgmt
      spec:
        clustercatalog: openstack-medium-catalog

