# permissions for end users to edit clusterdescriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterdescription-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-as-a-service
    app.kubernetes.io/part-of: kubernetes-as-a-service
    app.kubernetes.io/managed-by: kustomize
  name: clusterdescription-editor-role
rules:
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - clusterdescriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - clusterdescriptions/status
  verbs:
  - get
