---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - blueprints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - blueprints/finalizers
  verbs:
  - update
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - blueprints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - clusterdescriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - clusterdescriptions/finalizers
  verbs:
  - update
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - clusterdescriptions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - logicalclustercontrolplaneproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - logicalclustercontrolplaneproviders/finalizers
  verbs:
  - update
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - logicalclustercontrolplaneproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - logicalclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - logicalclusters/finalizers
  verbs:
  - update
- apiGroups:
  - intent.automation.dcn.ssu.ac.kr
  resources:
  - logicalclusters/status
  verbs:
  - get
  - patch
  - update
