apiVersion: automation.dcn.ssu.ac.kr/v1alpha1
kind: InfrastructureProfile
metadata:
  name: openstack-small-cluster
  type: Infrastructure
  namespace: default
  revision: 1.0.0
spec:
  profile: 
    name: clusterapi-resource-template-default
    type: Infrastructure
    revision: 1.0.0
  kubernetesVersion: v1.24.8
  controlPlaneMachineCount: 1
  workerMachineCount: 3
  controlplaneFlavor: m1.medium
  workerFlavor: m1.large
---
apiVersion: automation.dcn.ssu.ac.kr/v1alpha1
kind: InfrastructureProfile
metadata:
  name: clusterapi-resource-template-default
  type: Infrastructure
  namespace: default
  revision: 1.0.0
spec:
  filename: cluster-template.yaml
  url: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/release
  version: v0.7.0