apiVersion: intent.automation.dcn.ssu.ac.kr/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: cluster
    app.kubernetes.io/instance: cluster-sample
    app.kubernetes.io/part-of: kubernetes-as-a-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-as-a-service
  name: cluster-sample
spec:
  # TODO(user): Add fields here
