apiVersion: intent.automation.dcn.ssu.ac.kr/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: cluster
    app.kubernetes.io/instance: cluster-sample
    app.kubernetes.io/part-of: kubernetes-as-a-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-as-a-service
    automation.dcn.ssu.ac.kr/region: kr-seoul
    automation.dcn.ssu.ac.kr/zone: public
  name: cluster-sample2
spec:
  # TODO(user): Add fields here
  infrastructure:
      - provider: 
        name: openstack
        spec: 
          name: openstack-small-cluster
          type: ClusterTemplate
          revision: 1.0.0
        override:
          kubernetesVersion: v1.25.0
  network:
      - cni:
        name: flannel
        spec: 
          name: flannel-default
          type: CNITemplate
          revision: 1.0.0
        override:
          revision: 1.1.1
  software:
    - name: prometheus
      spec:
        name: prometheus-default
        type: ApplicationTemplate
        revison: 1.0.0