apiVersion: intent.automation.dcn.ssu.ac.kr/v1
kind: Blueprint
metadata:
  labels:
    app.kubernetes.io/name: blueprint
    app.kubernetes.io/instance: blueprint-sample
    app.kubernetes.io/part-of: kubernetes-as-a-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-as-a-service
  name: blueprint-sample
spec:
  # TODO(user): Add fields here
