apiVersion: intent.automation.dcn.ssu.ac.kr/v1
kind: ClusterCatalog
metadata:
  name: openstack-medium-catalog
  namespace: default
spec:
  infrastructure:
  - name: openstack-v1
    override:
      kubernetesVersion: v1.25.0
    spec:
      name: openstack-small-cluster
      type: ClusterTemplate
  network:
  - name: flannel-default
    spec:
      name: flannel-default
      type: CNITemplate
  software:
  - name: prometheus-v2.2
    spec:
      name: prometheus-default
      type: ApplicationTemplate