apiVersion: intent.automation.dcn.ssu.ac.kr/v1
kind: Blueprint
metadata:
  labels:
    app.kubernetes.io/name: blueprint
    app.kubernetes.io/instance: blueprint-sample
    app.kubernetes.io/part-of: kubernetes-as-a-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-as-a-service
  name: blueprint-sample-v1
  namespace: blueprints
  version: v1
spec:
  # TODO(user): Add fields here
  blueprint: 
      - {
          name: clusterapi-resource-template-default,
          version: v1,
          type: ClusterAPITemplate,
          revision: 1.0.0
      }
  values:
      kubernetesVersion: v1.24.8
      controlPlaneMachineCount: "1"
      workerMachineCount: "3"
      controlplaneFlavor: m1.medium
      workerFlavor: m1.large
