apiVersion: intent.automation.dcn.ssu.ac.kr/v1
kind: ClusterCatalog
metadata:
  name: openstack-medium-catalog
spec:
  infrastructure:
    - name: openstack-v1
      spec: 
        name: openstack-small-cluster
        type: ClusterTemplate
  network:
    - name: cilium-default
      spec: 
        name: cilium-default
        type: CNITemplate
  software:
    - name: prometheus-default
      spec: 
        name: prometheus-default
        type: ApplicationTemplate